name: Build Contents Nightly

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup enviroment
        run: |
         echo "::set-output name=sha_short::$(git rev-parse --short GITHUB_SHA)"
         mkdir ./Content 

      - name: Setup Git & Pull changes
        working-directory: ./Content
        run: |
         git init
         git config --local user.name "inc0der-bot"
         git config --local user.email "inc0der.bot@users.noreply.github.com"
         git remote add origin "https://inc0der:${{ secrets.GIT_TOKEN }}@github.com/inc0der-forks/paper-content"
         git pull origin develop

      - name: Build from source
        run: |
          npm install
          npm install typescript
          npm run build
  
      - name: Commit changes
        working-directory: ./Content
        continue-on-error: true
        run: |
         git add .
         git commit -m "Nightly: From commit sh ${{ steps.vars.outputs.sha_short }}"

      - name: Push changes
        working-directory: ./Content
        run: git push origin master:develop
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Content
          path: Content/

