name: Build Contents Nightly

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          npm install
          npm install typescript
          npm run build

      - name: Setup enviroment variables
        run: |
         echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  
      - name: Setup Git
        run: git config --global init.defaultBranch develop
    
      - name: Git Push to Content Repository
        working-directory: ./Content
        run: |
         git init
         git config user.name = "Paper Maker"
         git remote add origin https://github.com/inc0der-forks/paper-content.git
         git add .
         git commit -m "Nightly: From commit sh ${{ steps.vars.outputs.sha_short }}"
         git push origin develop --force
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Content
          path: Content/

