name: Build Contents

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          npm install
          npm install typescript
          npm run build

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Setup Git
        run: git config --global init.defaultBranch main
    
      - name: Git Push to Content Repository
        working-directory: ./Content
        run: |
         git init
         git config user.name = "Paper Maker"
         git remote add origin "https://github.com/inc0der-forks/paper-content.git"
         git add .
         git commit -m "Latest release ${{ env.TAG }}"
         git push origin main --force
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Content
          path: Content/
