name: Build Contents

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm install typescript
      - run: npm run build
      - run: git init Content/
      - run: git config user.name = "Paper Maker"
      - run: git remote add origin https://github.com/inc0der-forks/game-scripts-test.git
      - run: git push main --force
      - uses: actions/upload-artifact@v2
        with:
          name: Content
          path: Content/
